/*
 * MainJFrame.java
 *
 * Created on May 13, 2010, 10:52 PM
 */
package jaunty.copydetect;

import jaunty.copydetect.bean.SimilarityResult;

import java.awt.Font;
import java.io.File;
import java.util.Enumeration;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.UIManager;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.plaf.FontUIResource;

import org.apache.log4j.Logger;

/**
 * 
 * @author hellojinjie
 */
public class MainJFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 5479785434153661602L;
    private static final Logger log = Logger.getLogger(MainJFrame.class);

    /** Creates new form MainJFrame */
    public MainJFrame() {
        initGlobalFontSetting(new java.awt.Font("SimSun", 0, 13));
        initComponents();
        this.setLocation(100, 100);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jMenu1.setText("File");

        jMenu1.add(jMenuItem1);
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem3.setText("说明");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        jMenuItem1.setText("打开待检测文件");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenuItem2.setFont(new java.awt.Font("SimSun", 0, 13));
        jMenuItem2.setText("退出");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
                        900,
                        Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
                        581,
                        Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser chooser = new JFileChooser("." + File.separator + "data"
                + File.separator + "待检测论文");
        chooser.showOpenDialog(jMenu1);
        final File selectedFile = chooser.getSelectedFile();
        if (selectedFile != null) {
            // calculating();
            long time0 = System.currentTimeMillis();
            SimilarityMeasure similarityMeasure = new SimilarityMeasure(
                    selectedFile.getAbsolutePath());
            long time1 = System.currentTimeMillis();
            newPanel(similarityMeasure.measure(true));
            long time2 = System.currentTimeMillis();

            JOptionPane.showMessageDialog(this, "处理待比较数据集用时 " + (time1 - time0)
                    + " 毫秒\n抄袭检测用时 " + (time2 - time1) + " 毫秒", "用时统计",
                    JOptionPane.INFORMATION_MESSAGE);

        } else {
            log.debug("you do not choose any file");
        }
    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }// GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(null, "一种基于贝叶斯的抄袭检测方法",
                "一种基于贝叶斯的抄袭检测方法", JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_jMenuItem3ActionPerformed

    @SuppressWarnings("unchecked")
    public static void initGlobalFontSetting(Font fnt) {
        FontUIResource fontRes = new FontUIResource(fnt);
        for (Enumeration keys = UIManager.getDefaults().keys(); keys
                .hasMoreElements();) {
            Object key = keys.nextElement();
            Object value = UIManager.get(key);
            if (value instanceof FontUIResource) {
                UIManager.put(key, fontRes);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    /**
     * 生成一个面板，左边放待检测的论问段落，右边放待比较的论文的段落
     * 
     * 晕，，，这格式化后的代码是人读的吗？早知道就不格式化了
     * 
     * @param s1
     * @param s2
     */
    private void newPanel(List<SimilarityResult> data) {

        getContentPane().removeAll();

        JPanel[] panels = new JPanel[data.size()];

        for (int i = 0; i < data.size(); i++) {
            javax.swing.JPanel jPanel1 = new JPanel();
            javax.swing.JScrollPane jScrollPane1 = new JScrollPane();
            javax.swing.JScrollPane jScrollPane2 = new JScrollPane();
            javax.swing.JTextArea jTextArea1 = new JTextArea();
            javax.swing.JTextArea jTextArea2 = new JTextArea();
            javax.swing.JTextPane jTextPane = new JTextPane();

            jTextPane.setText(data.get(i).getParagraph().getPaper().getTitle()
                    + " 的 " + data.get(i).getParagraph().getParagraphId()
                    + " 段落与 "
                    + data.get(i).getTrainingData().getPaper().getTitle()
                    + " 的第 " + data.get(i).getTrainingData().getParagraphId()
                    + " 段落相似，相似度为 " + data.get(i).getSimilarity());
            jTextPane.setSize(700, 15);

            jTextArea1.setColumns(20);
            jTextArea1.setLineWrap(true);
            jTextArea1.setRows(5);
            jTextArea1.setText(data.get(i).getParagraph().getOriginalText());
            jScrollPane1.setViewportView(jTextArea1);

            jTextArea2.setColumns(20);
            jTextArea2.setLineWrap(true);
            jTextArea2.setRows(5);
            jTextArea2.setText(data.get(i).getTrainingData().getOriginalText());
            jScrollPane2.setViewportView(jTextArea2);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
                    jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout
                    .setHorizontalGroup(
                    jPanel1Layout
                            .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextPane,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, 750,
                                    Short.MAX_VALUE)
                            .addGroup(
                                    javax.swing.GroupLayout.Alignment.TRAILING,
                                    jPanel1Layout
                                            .createSequentialGroup()
                                            .addComponent(
                                                    jScrollPane1,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    400,
                                                    Short.MAX_VALUE)
                                            .addPreferredGap(
                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(
                                                    jScrollPane2,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    438,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)));
            jPanel1Layout
                    .setVerticalGroup(
                    jPanel1Layout
                            .createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                    jPanel1Layout
                                            .createSequentialGroup()
                                            .addComponent(jTextPane)
                                            .addPreferredGap(
                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(
                                                    jPanel1Layout
                                                            .createParallelGroup(
                                                                    javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(
                                                                    jScrollPane2,
                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                    227,
                                                                    Short.MAX_VALUE)
                                                            .addComponent(
                                                                    jScrollPane1,
                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                    227,
                                                                    Short.MAX_VALUE))));
            panels[i] = jPanel1;
        }

        JScrollPane jScrollPane = new JScrollPane();

        JPanel jPanel0 = new JPanel();
        javax.swing.GroupLayout layout1 = new javax.swing.GroupLayout(jPanel0);
        jPanel0.setLayout(layout1);
        ParallelGroup parallelGroup1 = layout1
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        for (int i = 0; i < panels.length; i++) {
            parallelGroup1.addComponent(panels[i],
                    javax.swing.GroupLayout.Alignment.TRAILING,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
        }
        layout1.setHorizontalGroup(parallelGroup1);

        ParallelGroup parallelGroup2 = layout1
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        SequentialGroup sequentialGroup = layout1.createSequentialGroup();
        for (int i = 0; i < panels.length; i++) {
            sequentialGroup.addComponent(panels[i],
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE);
        }
        // sequentialGroup.addContainerGap(298, Short.MAX_VALUE);
        parallelGroup2.addGroup(sequentialGroup);
        layout1.setVerticalGroup(parallelGroup2);

        jScrollPane.setViewportView(jPanel0);

        // /////////////////////////////////////////////////////////////////////////////////
        javax.swing.GroupLayout layout2 = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout2);
        layout2.setHorizontalGroup(
                layout2.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                        layout2.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(
                                        jScrollPane,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        900,
                                        Short.MAX_VALUE).addContainerGap()));
        layout2.setVerticalGroup(
                layout2.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                        layout2.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(
                                        jScrollPane,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        581,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
        pack();

    }

    /**
     * 这个函数竟然没有像我想像的那样工作。。。。
     */
    private void calculating() {

        getContentPane().removeAll();

        JLabel jLabel1 = new JLabel();
        jLabel1.setText("计算中......");

        JPanel jPanel1 = new JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
                jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(381, 381, 381)
                                .addComponent(jLabel1)
                                .addContainerGap(392, Short.MAX_VALUE))
                );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jLabel1)
                                .addContainerGap(345, Short.MAX_VALUE))
                );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                );

        pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
